name: publish
on:
  push:
    branches: [ "master" ]
#  pull_request:
#    branches: [ "master" ]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - name: Login to GitHub Container Registry
      uses: docker/login-action@v1
      with:
        registry: ghcr.io
        username: ${{ github.actor }}
        password: ${{ secrets.GIT_DOCKER_PAT }}
    - name: Build the Docker image
      run: |
        docker build . --tag ghcr.io/kspa/quote:latest
        docker push ghcr.io/kspa/quote:latest
